### ISSUE TITLE
some on received datas are ignored

### ISSUE THREAD

**Issue by tdebarochez** [rauchg/node.websocket.js#1]
Run following code in client side :
var i = 0; while (i < 30) {webSocket.send('blah'); ++i; }
In server side, you will get just one or two call to module.onData methode. 

To correct, replace line 25 :
-    dataMatch = /^\u0000(.+)\ufffd$/,
-    dataMatch = /^\u0000([^\ufffd]+)\ufffd$/,

And replace line 144 :
-  var chunks = data.replace(/^(\u0000)|(\ufffd)$/g, '').split('\ufffd\u0000');
-  for (var i = 0, l = chunks.length; i < l; ++i) {
-    this.module.onData(chunks[i], this);
-  }
-  this.module.onData(match[1], this);

**Comment by rauchg** [comment]
Committed. Thanks tdebarochez.
