### ISSUE TITLE
Websocket in two tabs stops working when closing the first tab window

### ISSUE THREAD

**Issue by rgl** [rauchg/node.websocket.js#2]
I'm trying out node.websocket with latest chromium builds, but its not quite working in this scenario:
1. Open a page with an websocket that periodically sends data to the browser
   (eg. it sends the current date 1 time per second, like the runserver.js that ships with node.websocket).
2. Open the same page in a new tab.
3. Close the first tab (by clicking the tab close button).
4. See that the remaining tab window stops receiving data in the web socket.

I've opened a ticket with chromium (https://code.google.com/p/chromium/issues/detail?id=30668) and another with webkit (https://bugs.webkit.org/show_bug.cgi?id=32774), but maybe this is really a problem with node.websocket because I've tried an equivalent test against a ruby web socket server
(http://github.com/igrigorik/em-websocket) and it worked fine.

**Comment by rauchg** [comment]
- Changed the way we work with modules. Modules now have to implement classes. Closed by 954835b2e8fa2b82b4bc558f3090497be4b7a2de
- OCD-related work
- Adjusted README to reflect new API changes
