### ISSUE TITLE
Bug in Connection.prototype.send

### ISSUE THREAD

**Issue by telendt** [rauchg/node.websocket.js#6]
Quote from Node.js doc:

> Node supports 3 string encodings. UTF-8 ("utf8"), ASCII ("ascii"), and Binary ("binary"). "ascii" and "binary" only look at the first 8 bits of the 16bit JavaScript string characters.

Because there no way to write "0xFF" byte in UTF-8 encoding, the following code is invalid:
    this.socket.write('\u0000' + data + '\uffff');
It could be replaced with:
    this.socket.write('\u0000' + data, 'utf8');
    this.socket.write('\uffff', 'binary');
Or better (warning - uses internal, undocumented Node.js API):
    var Buffer = require('buffer').Buffer;
    var bytes = Buffer.byteLength(data, 'utf8') + 2;
    var buffer = new Buffer(bytes);
    buffer[0] = 0;
    buffer.utf8Write(data, 1);
    buffer[bytes-1] = 0xff;
    this.socket.write(buffer);

**Comment by rauchg** [comment]
Can you fork and add this to Socket.IO-node ? I'm gonna be maintaining Socket.IO-node exclusively from now on.

http://github.com/RosePad/Socket.IO-node/
